@host = http://localhost:3000


### Health Check
GET {{host}}/api/docs HTTP/1.1
content-type: application/json

### GET Status
GET {{host}}/api/status HTTP/1.1

###
POST {{host}}/api/cnab240/fornecedores HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}