@hostlocal = http://localhost:3000/



GET {{hostlocal}}api/doc HTTP/1.1
Content-type: application/json

###
GET http://localhost:3000/api/status  HTTP/1.1
content-Type: application/json"
###
###

POST {{hostlocal}}api/cnab240/fornecedores HTTP/1.1
Content-Type: application/json

###
POST {{hostlocal}}api/cnab240/salarios HTTP/1.1
content-Type: application/json" 

{
   "empresa":{
      "tipo_inscricao":"2",
      "inscricao_numero":"12345678901234",
      "nome":"EMPRESA TESTE",
      "agencia":"1234",
      "conta":"123456",
      "dac":"7"
   },
   "pagamentos":[
      {
         "tipo_inscricao":"1",
         "inscricao_numero":"98765432109",
         "nome":"FUNCIONARIO TESTE",
         "valor":3000.00,
         "data_pagamento":"20240315"
      }
   ]
}