/**
 * Constantes e enumerações para o CNAB 240
 * Baseado no Manual Técnico SISPAG CNAB 240 (versão 086)
 */

/**
 * Códigos de Bancos
 */
const BANCOS = {
    SANTANDER: '033',
    BRADESCO: '237',
    ITAU: '341',
    CAIXA: '104',
    BRASIL: '001'
};

/**
 * Tipos de Registro
 */
const TIPOS_REGISTRO = {
    HEADER_ARQUIVO: '0',
    HEADER_LOTE: '1',
    DETALHE: '3',
    TRAILER_LOTE: '5',
    TRAILER_ARQUIVO: '9'
};

/**
 * Tipos de Operação
 */
const TIPOS_OPERACAO = {
    CREDITO: 'C',
    DEBITO: 'D'
};

/**
 * Tipos de Serviço
 */
const TIPOS_SERVICO = {
    COBRANCA: '01',
    BLOQUETO: '03',
    CONCILIACAO: '04',
    REMESSA: '30',
    RETORNO: '31',
    PAGAMENTO_FORNECEDOR: '40',
    PAGAMENTO_SALARIO: '41',
    PAGAMENTO_HONORARIOS: '42',
    PAGAMENTO_BOLETO: '43',
    PAGAMENTO_DIVERSOS: '44',
    PAGAMENTO_TRIBUTOS: '45',
    PAGAMENTO_GPS: '46',
    PAGAMENTO_IPVA: '47',
    PAGAMENTO_IPTU: '48',
    PAGAMENTO_LICENCIAMENTO: '49',
    PAGAMENTO_DPVAT: '50',
    PAGAMENTO_DARF: '51',
    PAGAMENTO_GARE: '52',
    PAGAMENTO_FGTS: '53',
    PAGAMENTO_DARJ: '54',
    PAGAMENTO_DARE: '55',
    PAGAMENTO_DAS: '56',
    PAGAMENTO_IPVA_PARCELA: '57',
    PAGAMENTO_IPTU_PARCELA: '58',
    PAGAMENTO_LICENCIAMENTO_PARCELA: '59',
    PAGAMENTO_DPVAT_PARCELA: '60',
    PAGAMENTO_DARF_PARCELA: '61',
    PAGAMENTO_GARE_PARCELA: '62',
    PAGAMENTO_FGTS_PARCELA: '63',
    PAGAMENTO_DARJ_PARCELA: '64',
    PAGAMENTO_DARE_PARCELA: '65',
    PAGAMENTO_DAS_PARCELA: '66',
    PAGAMENTO_IPVA_PARCELA_UNICA: '67',
    PAGAMENTO_IPTU_PARCELA_UNICA: '68',
    PAGAMENTO_LICENCIAMENTO_PARCELA_UNICA: '69',
    PAGAMENTO_DPVAT_PARCELA_UNICA: '70',
    PAGAMENTO_DARF_PARCELA_UNICA: '71',
    PAGAMENTO_GARE_PARCELA_UNICA: '72',
    PAGAMENTO_FGTS_PARCELA_UNICA: '73',
    PAGAMENTO_DARJ_PARCELA_UNICA: '74',
    PAGAMENTO_DARE_PARCELA_UNICA: '75',
    PAGAMENTO_DAS_PARCELA_UNICA: '76',
    PAGAMENTO_IPVA_PARCELA_UNICA_ANTECIPADA: '77',
    PAGAMENTO_IPTU_PARCELA_UNICA_ANTECIPADA: '78',
    PAGAMENTO_LICENCIAMENTO_PARCELA_UNICA_ANTECIPADA: '79',
    PAGAMENTO_DPVAT_PARCELA_UNICA_ANTECIPADA: '80',
    PAGAMENTO_DARF_PARCELA_UNICA_ANTECIPADA: '81',
    PAGAMENTO_GARE_PARCELA_UNICA_ANTECIPADA: '82',
    PAGAMENTO_FGTS_PARCELA_UNICA_ANTECIPADA: '83',
    PAGAMENTO_DARJ_PARCELA_UNICA_ANTECIPADA: '84',
    PAGAMENTO_DARE_PARCELA_UNICA_ANTECIPADA: '85',
    PAGAMENTO_DAS_PARCELA_UNICA_ANTECIPADA: '86',
    PAGAMENTO_IPVA_PARCELA_UNICA_ANTECIPADA_2: '87',
    PAGAMENTO_IPTU_PARCELA_UNICA_ANTECIPADA_2: '88',
    PAGAMENTO_LICENCIAMENTO_PARCELA_UNICA_ANTECIPADA_2: '89',
    PAGAMENTO_DPVAT_PARCELA_UNICA_ANTECIPADA_2: '90',
    PAGAMENTO_DARF_PARCELA_UNICA_ANTECIPADA_2: '91',
    PAGAMENTO_GARE_PARCELA_UNICA_ANTECIPADA_2: '92',
    PAGAMENTO_FGTS_PARCELA_UNICA_ANTECIPADA_2: '93',
    PAGAMENTO_DARJ_PARCELA_UNICA_ANTECIPADA_2: '94',
    PAGAMENTO_DARE_PARCELA_UNICA_ANTECIPADA_2: '95',
    PAGAMENTO_DAS_PARCELA_UNICA_ANTECIPADA_2: '96',
    PAGAMENTO_IPVA_PARCELA_UNICA_ANTECIPADA_3: '97',
    PAGAMENTO_IPTU_PARCELA_UNICA_ANTECIPADA_3: '98',
    PAGAMENTO_LICENCIAMENTO_PARCELA_UNICA_ANTECIPADA_3: '99'
};

/**
 * Formas de Pagamento
 */
const FORMAS_PAGAMENTO = {
    CREDITO_CONTA: '01',
    CHEQUE_PAGAMENTO: '02',
    DOC_TED: '03',
    CARTAO_SALARIO: '04',
    CREDITO_POUPANCA: '05',
    OP_DISPOSICAO: '10',
    PAGAMENTO_CONTAS: '11',
    TED_OUTRA_TITULARIDADE: '12',
    TED_MESMA_TITULARIDADE: '13',
    TED_OUTRA_TITULARIDADE_POUPANCA: '14',
    TED_MESMA_TITULARIDADE_POUPANCA: '15',
    TED_OUTRA_TITULARIDADE_INVESTIMENTO: '16',
    TED_MESMA_TITULARIDADE_INVESTIMENTO: '17',
    PIX: '18'
};

/**
 * Códigos de Movimento
 */
const CODIGOS_MOVIMENTO = {
    INCLUSAO: '000',
    ALTERACAO: '001',
    EXCLUSAO: '002',
    LIQUIDACAO: '003',
    BAIXA: '004',
    RETIRADA: '005',
    PAGAMENTO: '006',
    RECUSA: '007',
    SUSPENSAO: '008',
    REATIVACAO: '009',
    CANCELAMENTO: '010',
    ALTERACAO_VALOR: '011',
    ALTERACAO_DATA: '012',
    ALTERACAO_FORMA: '013',
    ALTERACAO_DADOS: '014',
    ALTERACAO_DOCUMENTO: '015',
    ALTERACAO_ENDERECO: '016',
    ALTERACAO_BANCO: '017',
    ALTERACAO_AGENCIA: '018',
    ALTERACAO_CONTA: '019',
    ALTERACAO_DV: '020',
    ALTERACAO_NOME: '021',
    ALTERACAO_CPF_CNPJ: '022',
    ALTERACAO_TIPO: '023',
    ALTERACAO_VALOR_MINIMO: '024',
    ALTERACAO_VALOR_MAXIMO: '025',
    ALTERACAO_QUANTIDADE: '026',
    ALTERACAO_PERIODO: '027',
    ALTERACAO_DIA: '028',
    ALTERACAO_MES: '029',
    ALTERACAO_ANO: '030',
    ALTERACAO_HORA: '031',
    ALTERACAO_MINUTO: '032',
    ALTERACAO_SEGUNDO: '033',
    ALTERACAO_MILISEGUNDO: '034',
    ALTERACAO_DATA_HORA: '035',
    ALTERACAO_DATA_HORA_MINUTO: '036',
    ALTERACAO_DATA_HORA_SEGUNDO: '037',
    ALTERACAO_DATA_HORA_MILISEGUNDO: '038',
    ALTERACAO_DATA_HORA_MINUTO_SEGUNDO: '039',
    ALTERACAO_DATA_HORA_MINUTO_SEGUNDO_MILISEGUNDO: '040',
    ALTERACAO_DATA_HORA_SEGUNDO_MILISEGUNDO: '041',
    ALTERACAO_DATA_HORA_MILISEGUNDO: '042',
    ALTERACAO_DATA_HORA_MINUTO_MILISEGUNDO: '043',
    ALTERACAO_DATA_HORA_SEGUNDO: '044',
    ALTERACAO_DATA_HORA_MINUTO: '045',
    ALTERACAO_DATA_HORA: '046',
    ALTERACAO_MILISEGUNDO: '047',
    ALTERACAO_SEGUNDO: '048',
    ALTERACAO_MINUTO: '049',
    ALTERACAO_HORA: '050',
    ALTERACAO_ANO: '051',
    ALTERACAO_MES: '052',
    ALTERACAO_DIA: '053',
    ALTERACAO_PERIODO: '054',
    ALTERACAO_QUANTIDADE: '055',
    ALTERACAO_VALOR_MAXIMO: '056',
    ALTERACAO_VALOR_MINIMO: '057',
    ALTERACAO_TIPO: '058',
    ALTERACAO_CPF_CNPJ: '059',
    ALTERACAO_NOME: '060',
    ALTERACAO_DV: '061',
    ALTERACAO_CONTA: '062',
    ALTERACAO_AGENCIA: '063',
    ALTERACAO_BANCO: '064',
    ALTERACAO_ENDERECO: '065',
    ALTERACAO_DOCUMENTO: '066',
    ALTERACAO_DADOS: '067',
    ALTERACAO_FORMA: '068',
    ALTERACAO_DATA: '069',
    ALTERACAO_VALOR: '070',
    CANCELAMENTO: '071',
    REATIVACAO: '072',
    SUSPENSAO: '073',
    RECUSA: '074',
    PAGAMENTO: '075',
    RETIRADA: '076',
    BAIXA: '077',
    LIQUIDACAO: '078',
    EXCLUSAO: '079',
    ALTERACAO: '080',
    INCLUSAO: '081'
};

/**
 * Códigos de Ocorrência
 */
const CODIGOS_OCORRENCIA = {
    ENTRADA_CONFIRMADA: '00',
    ENTRADA_REJEITADA: '01',
    TRANSFERENCIA_CARTEIRA: '02',
    TRANSFERENCIA_CONFIRMADA: '03',
    TRANSFERENCIA_REJEITADA: '04',
    ALTERACAO_DADOS: '05',
    LIQUIDACAO: '06',
    CONFIRMACAO_RECEBIMENTO: '07',
    CONFIRMACAO_INSTRUCAO: '08',
    BAIXA: '09',
    TITULO_EM_CARTEIRA: '10',
    TITULO_EM_CARTEIRA_2: '11',
    TITULO_EM_CARTEIRA_3: '12',
    TITULO_EM_CARTEIRA_4: '13',
    TITULO_EM_CARTEIRA_5: '14',
    TITULO_EM_CARTEIRA_6: '15',
    TITULO_EM_CARTEIRA_7: '16',
    TITULO_EM_CARTEIRA_8: '17',
    TITULO_EM_CARTEIRA_9: '18',
    TITULO_EM_CARTEIRA_10: '19',
    TITULO_EM_CARTEIRA_11: '20',
    TITULO_EM_CARTEIRA_12: '21',
    TITULO_EM_CARTEIRA_13: '22',
    TITULO_EM_CARTEIRA_14: '23',
    TITULO_EM_CARTEIRA_15: '24',
    TITULO_EM_CARTEIRA_16: '25',
    TITULO_EM_CARTEIRA_17: '26',
    TITULO_EM_CARTEIRA_18: '27',
    TITULO_EM_CARTEIRA_19: '28',
    TITULO_EM_CARTEIRA_20: '29',
    TITULO_EM_CARTEIRA_21: '30',
    TITULO_EM_CARTEIRA_22: '31',
    TITULO_EM_CARTEIRA_23: '32',
    TITULO_EM_CARTEIRA_24: '33',
    TITULO_EM_CARTEIRA_25: '34',
    TITULO_EM_CARTEIRA_26: '35',
    TITULO_EM_CARTEIRA_27: '36',
    TITULO_EM_CARTEIRA_28: '37',
    TITULO_EM_CARTEIRA_29: '38',
    TITULO_EM_CARTEIRA_30: '39',
    TITULO_EM_CARTEIRA_31: '40',
    TITULO_EM_CARTEIRA_32: '41',
    TITULO_EM_CARTEIRA_33: '42',
    TITULO_EM_CARTEIRA_34: '43',
    TITULO_EM_CARTEIRA_35: '44',
    TITULO_EM_CARTEIRA_36: '45',
    TITULO_EM_CARTEIRA_37: '46',
    TITULO_EM_CARTEIRA_38: '47',
    TITULO_EM_CARTEIRA_39: '48',
    TITULO_EM_CARTEIRA_40: '49',
    TITULO_EM_CARTEIRA_41: '50',
    TITULO_EM_CARTEIRA_42: '51',
    TITULO_EM_CARTEIRA_43: '52',
    TITULO_EM_CARTEIRA_44: '53',
    TITULO_EM_CARTEIRA_45: '54',
    TITULO_EM_CARTEIRA_46: '55',
    TITULO_EM_CARTEIRA_47: '56',
    TITULO_EM_CARTEIRA_48: '57',
    TITULO_EM_CARTEIRA_49: '58',
    TITULO_EM_CARTEIRA_50: '59',
    TITULO_EM_CARTEIRA_51: '60',
    TITULO_EM_CARTEIRA_52: '61',
    TITULO_EM_CARTEIRA_53: '62',
    TITULO_EM_CARTEIRA_54: '63',
    TITULO_EM_CARTEIRA_55: '64',
    TITULO_EM_CARTEIRA_56: '65',
    TITULO_EM_CARTEIRA_57: '66',
    TITULO_EM_CARTEIRA_58: '67',
    TITULO_EM_CARTEIRA_59: '68',
    TITULO_EM_CARTEIRA_60: '69',
    TITULO_EM_CARTEIRA_61: '70',
    TITULO_EM_CARTEIRA_62: '71',
    TITULO_EM_CARTEIRA_63: '72',
    TITULO_EM_CARTEIRA_64: '73',
    TITULO_EM_CARTEIRA_65: '74',
    TITULO_EM_CARTEIRA_66: '75',
    TITULO_EM_CARTEIRA_67: '76',
    TITULO_EM_CARTEIRA_68: '77',
    TITULO_EM_CARTEIRA_69: '78',
    TITULO_EM_CARTEIRA_70: '79',
    TITULO_EM_CARTEIRA_71: '80',
    TITULO_EM_CARTEIRA_72: '81',
    TITULO_EM_CARTEIRA_73: '82',
    TITULO_EM_CARTEIRA_74: '83',
    TITULO_EM_CARTEIRA_75: '84',
    TITULO_EM_CARTEIRA_76: '85',
    TITULO_EM_CARTEIRA_77: '86',
    TITULO_EM_CARTEIRA_78: '87',
    TITULO_EM_CARTEIRA_79: '88',
    TITULO_EM_CARTEIRA_80: '89',
    TITULO_EM_CARTEIRA_81: '90',
    TITULO_EM_CARTEIRA_82: '91',
    TITULO_EM_CARTEIRA_83: '92',
    TITULO_EM_CARTEIRA_84: '93',
    TITULO_EM_CARTEIRA_85: '94',
    TITULO_EM_CARTEIRA_86: '95',
    TITULO_EM_CARTEIRA_87: '96',
    TITULO_EM_CARTEIRA_88: '97',
    TITULO_EM_CARTEIRA_89: '98',
    TITULO_EM_CARTEIRA_90: '99'
};

// Tipos de serviço
const SERVICE_TYPES = {
  COBRANCA: '01',
  PAGAMENTO_FORNECEDORES: '20',
  PAGAMENTO_SALARIOS: '30',
  PAGAMENTO_TRIBUTOS: '22',
  PAGAMENTO_PIX: '90'
};

// Tipos de inscrição
const INSCRIPTION_TYPES = {
  CPF: '1',
  CNPJ: '2'
};

// Versões do layout
const LAYOUT_VERSIONS = {
  CNAB240: '086',
  LOTE: '045'
};

// Tipos de segmento
const SEGMENT_TYPES = {
  A: 'A',
  B: 'B',
  C: 'C',
  P: 'P',
  Q: 'Q',
  R: 'R'
};

// Tipos de chave PIX
const PIX_KEY_TYPES = {
  CPF_CNPJ: '1',
  EMAIL: '2',
  CELULAR: '3',
  ALEATORIA: '4'
};

// Finalidades do lote
const BATCH_PURPOSES = {
  PAGAMENTO_FORNECEDORES: 'PAGAMENTO A FORNECEDORES',
  PAGAMENTO_SALARIOS: 'PAGAMENTO DE SALARIOS',
  PAGAMENTO_TRIBUTOS: 'PAGAMENTO DE TRIBUTOS',
  PAGAMENTO_PIX: 'PAGAMENTO VIA PIX'
};

// Códigos de movimento
const MOVEMENT_CODES = {
  INCLUSAO: '000',
  EXCLUSAO: '999'
};

// Códigos de finalidade
const PURPOSE_CODES = {
  CREDITO_EM_CONTA: '01',
  PAGAMENTO_FORNECEDORES: '02',
  PAGAMENTO_SALARIOS: '03',
  PAGAMENTO_TRIBUTOS: '04',
  PAGAMENTO_PIX: '05'
};

// Códigos de aviso
const NOTICE_CODES = {
  NAO_EMITE: '0',
  EMITE: '2'
};

// Códigos de finalidade TED (específicos Santander)
const TED_PURPOSE_CODES = {
  CREDITO_EM_CONTA: '00001',
  PAGAMENTO_FORNECEDORES: '00002',
  PAGAMENTO_SALARIOS: '00006',
  PAGAMENTO_HONORARIOS: '00010',
  PAGAMENTO_BOLSA_AUXILIO: '00011',
  PAGAMENTO_DIVIDENDOS: '00100',
  PAGAMENTO_COMISSOES: '00101',
  PAGAMENTO_ALUGUEIS: '00102'
};

// Códigos de finalidade de pagamento (específicos Santander)
const PAYMENT_PURPOSE_CODES = {
  FOLHA_MENSAL: '101',
  FERIAS: '102',
  DECIMO_TERCEIRO: '103',
  PLR: '104',
  RESCISAO: '105',
  FOLHA_COMPLEMENTAR: '106',
  PENSAO_ALIMENTICIA: '107'
};

// Exporta as constantes
module.exports = {
  BANCOS,
  TIPOS_REGISTRO,
  TIPOS_OPERACAO,
  TIPOS_SERVICO,
  FORMAS_PAGAMENTO,
  CODIGOS_MOVIMENTO,
  CODIGOS_OCORRENCIA,
  SERVICE_TYPES,
  INSCRIPTION_TYPES,
  LAYOUT_VERSIONS,
  SEGMENT_TYPES,
  PIX_KEY_TYPES,
  BATCH_PURPOSES,
  MOVEMENT_CODES,
  PURPOSE_CODES,
  NOTICE_CODES,
  TED_PURPOSE_CODES,
  PAYMENT_PURPOSE_CODES
};
